name = "sports-report-worker"
main = "worker.js"           # <-- your Worker script file
compatibility_date = "2025-10-06"
type = "javascript"          # or "webpack" / "modules" if using modules

# Optional: KV namespace binding
kv_namespaces = [
  { binding = "GlobalStorage", id = "5ee5ae413b0e4196a234b2f72ae4e002" }
]
